"""Add email OTP table

Revision ID: d6418e5b9228
Revises: 
Create Date: 2025-06-15 15:42:52.673766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6418e5b9228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CLIENT',
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('user_name'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('client')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('create', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('update', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('delete', sa.Boolean(), nullable=True))
        batch_op.drop_column('UPDATE')
        batch_op.drop_column('CREATE')
        batch_op.drop_column('READ')
        batch_op.drop_column('DELETE')
        batch_op.drop_column('USER_NAME')
        batch_op.drop_column('PASSWORD')
        batch_op.drop_column('EMAIL')

    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('insurance_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('surveyor_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('garage_location', sa.String(length=255), nullable=True))
        batch_op.alter_column('remarks',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_column('Vehicle_number')
        batch_op.drop_column('Surveyor_name')
        batch_op.drop_column('Client_Name')
        batch_op.drop_column('Insurance_company')
        batch_op.drop_column('Garage_location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claim', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Garage_location', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('Insurance_company', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Client_Name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Surveyor_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('Vehicle_number', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('remarks',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               existing_nullable=True)
        batch_op.drop_column('garage_location')
        batch_op.drop_column('surveyor_name')
        batch_op.drop_column('insurance_company')
        batch_op.drop_column('client_name')
        batch_op.drop_column('vehicle_number')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('EMAIL', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('PASSWORD', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('USER_NAME', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('DELETE', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('READ', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('CREATE', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('UPDATE', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('delete')
        batch_op.drop_column('read')
        batch_op.drop_column('update')
        batch_op.drop_column('create')
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('user_name')

    op.create_table('client',
    sa.Column('USER_NAME', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('NAME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('EMAIL', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PASSWORD', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PHONE', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ADDRESS', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('USER_NAME'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('CLIENT')
    # ### end Alembic commands ###
